apiVersion: v1
kind: Service
metadata:
  name: kubecost-dashboard-lb
  namespace: kubecost
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app.kubernetes.io/name: cost-analyzer
    app.kubernetes.io/component: cost-analyzer
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
