apiVersion: v1
kind: Service
metadata:
  name: goldilocks-dashboard-lb
  namespace: goldilocks
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app.kubernetes.io/name: goldilocks
    app.kubernetes.io/component: dashboard
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
