apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: searxng-network-policy
  namespace: vllm-inference
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: searxng
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: hr-webui
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: general-webui
