apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: hr-webui
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-3:513158237195:certificate/7eb6e65e-9c74-42be-a0ae-6fc648603058
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Blueprint=automode-cluster,Environment=automode-cluster,Owner=ITDD-ITSMKube-SharePoint,Project=gar-gpt,CostCenter=engineering,Component=networking,Service=openwebui,Tenant=hr"
spec:
  selector:
    app.kubernetes.io/component: open-webui
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080

